### ISSUE TITLE
Dynamic Thread Predicate doesn't work on thread that installs BlockHound

### ISSUE THREAD

**Issue by wburns** [reactor/BlockHound#121]
## Expected Behavior
When I set all threads to be dynamic I expect the thread predicate to be called whenever a blocking call is found.

## Actual Behavior
The STATE local variable in BlockHoundRuntime is set when it creates a test thread and has the default dynamic predicate defined, thus not allowing the invoking thread to use dynamic predicates.

## Steps to Reproduce

```java
public class CoreTestBlockHoundIntegration implements BlockHoundIntegration {
   public static final ThreadLocal<Boolean> checkBlocking = ThreadLocal.withInitial(() -> Boolean.FALSE);
   @Override
   public void applyTo(BlockHound.Builder builder) {
      builder.addDynamicThreadPredicate(t -> true);
      builder.nonBlockingThreadPredicate(threadPredicate -> threadPredicate.or(t -> {
         return checkBlocking.get() == Boolean.TRUE;
      }));
   }   
}
@Test
public void nonBlockingCase() throws TimeoutException {
   Thread.sleep(100);
   CoreTestBlockHoundIntegration.checkBlocking.set(Boolean.TRUE);
   try {
     // Should fail here but doesn't
     Thread.sleep(100);
   } finally {
      CoreTestBlockHoundIntegration.checkBlocking.set(Boolean.FALSE);      
   }
}
```

Here is the stack trace showing the BlockHoundRuntime.STATE variable being initialized at the incorrect time since the ClassLoader.loadClass method is instrumented it initializes the STATE. But since it still has the default dynamic thread predicate it always sets it to false.

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at reactor.blockhound.BlockHoundRuntime.lambda$static$0(BlockHoundRuntime.java:62)
	  at reactor.blockhound.BlockHoundRuntime$$Lambda$131.1556520190.get(Unknown Source:-1)
	  at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	  at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	  at java.lang.ThreadLocal.get(ThreadLocal.java:172)
	  at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	  at reactor.blockhound.TestThread.<init>(TestThread.java:29)
	  at reactor.blockhound.BlockHound$Builder.testInstrumentation(BlockHound.java:415)
	  at reactor.blockhound.BlockHound$Builder.install(BlockHound.java:401)
	  at reactor.blockhound.BlockHound.install(BlockHound.java:94)
```
## Possible Solution
The BlockHoundRuntime.STATE thread local should be reset after it has set the proper dynamic thread predicate.

This can be done at https://github.com/reactor/BlockHound/blob/b9c60096113bba2448fe00d90eff791de14495a2/agent/src/main/java/reactor/blockhound/BlockHound.java#L405

For the time being I have to spawn a thread that just invokes BlockHound.install, which is quite ugly.

```java
      Thread otherThread = new Thread(() -> BlockHound.install());
      otherThread.start();
      try {
         otherThread.join();
      } catch (InterruptedException e) {
         throw new RuntimeException(e);
      }
```

## Your Environment

* Reactor version(s) used: Blockhound 1.0.3.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 
* OS and version (eg `uname -a`):

**Comment by bsideup** [comment]
Hi @wburns,

Thanks for reporting, I will look into it.

Meanwhile, could you please clarify why you need this?
> When I set all threads to be dynamic

**Comment by wburns** [comment]
> Meanwhile, could you please clarify why you need this?
> 
> > When I set all threads to be dynamic

That just simplifies the example. However the core problem is if the thread which installs BlockHound runs the test then it runs into this issue, from say IDEA.

**Comment by bsideup** [comment]
I understand that this is a simplification, but I wanted to know what are you trying to achieve, perhaps there is an easier way.

**Comment by wburns** [comment]
The core of what I want to do is I am running testng and I may invoke some code that should be non blocking. However because this is invoked in the testng thread it can block for other reasons. I don't want to have to define all the exclusions for a test framework to test such things.

Now one way to fix this is to invoke the code I want to not block solely in a separate thread, but this makes the tests quite hard to write and maintain. And not to mention can run into other bugs as I have to change threads for an operation that wouldn't normally.

I saw you added dynamic test predicates in 1.0.3 and thought I could utilize that so I could mark specific blocks of code as it shouldn't block during it or even replace components with delegating wrappers to ensure the underlying method call doesn't block. But the calling code itself can still block as necessary.

For example this can be a way to define a given code, invoked in the same thread would be checked for non blocking

```java
   public static <V> V ensureNonBlocking(Supplier<V> supplier) {
      isNonBlocking.set(Boolean.TRUE);
      try {
         return supplier.get();
      } finally {
         isNonBlocking.set(Boolean.FALSE);
      }
   }
```
The `isNonBlocking` variable is a ThreadLocal which is checked by the non blocking thread predicate  when the thread is dynamic.

I guess if you had some sort of static method in BlockHound to say ensure this code is non blocking similar to above, would work for me as well.

**Comment by wburns** [comment]
So with a method like that I can write a delegate wrapper that allows me to make sure whenever this object is invoked that it doesn't block.

```java
public abstract class EnsureNonBlockingStore<K, V> extends DelegatingNonBlockingStore<K, V> implements NonBlockingStore<K, V> {

   protected abstract NonBlockingStore<K, V> delegate();
   
   @Override
   public CompletionStage<Void> start(InitializationContext ctx) {
      return TestHelper.ensureNonBlocking(() -> delegate().start(ctx));
   }

   @Override
   public CompletionStage<Void> stop() {
      return TestHelper.ensureNonBlocking(() -> delegate().stop());
   }

  ... ommitted rest of methods ...
}
```

The test code however could still be blocking, such as `store.stop().toCompletableFuture().join()`.

**Comment by bsideup** [comment]
@wburns sorry, pressed wrong button 😅

> Now one way to fix this is to invoke the code I want to not block solely in a separate thread, but this makes the tests quite hard to write and maintain

Since you can do it in `TestHelper.ensureNonBlocking`, is it really that hard? That's the way I'd recommend.

That said, I kinda like the idea of dynamically changing the current thread's blocking status in tests, will try to fix it.

**Comment by wburns** [comment]
> Since you can do it in `TestHelper.ensureNonBlocking`, is it really that hard? That's the way I'd recommend.

Oh I am perfectly fine doing this. That isn't the problem. The problem is the dynamic predicate is evaluated with the default dynamic predicate which is false on the invoking thread because it loads a Class. The invoking thread can therefore never have dynamic predicates. Which is why I have to use the ugly workaround of spawning a thread for sole purpose of installing BlockHound.

I created https://github.com/reactor/BlockHound/pull/123 which should show how it could be resolved.

**Comment by bsideup** [comment]
@wburns I just submitted https://github.com/reactor/BlockHound/pull/124 that should solve it, please have a look

**Comment by wburns** [comment]
Looks good to me @bsideup, thanks!

**Comment by bsideup** [comment]
@wburns thanks for having a look 💯 

Once merged, it will be available as `1.0.4.BUILD-SNAPSHOT`.
Alternatively, you can use https://jitpack.io to grab it directly from the PR :)

**Comment by wburns** [comment]
Luckily the workaround is simple enough (albeit ugly), I can just wait for 1.0.4.RELEASE.

Thanks again!

**Comment by bsideup** [comment]
@wburns released 👍

**Comment by wburns** [comment]
Thanks!
