### ISSUE TITLE
outputStream.write(byteArray) is not detected as blocking call

### ISSUE THREAD

**Issue by rejuan** [reactor/BlockHound#134]
I am trying to use BlockHound in my spring boot application to detect the blocking scenario but it can't detect Logback  `ch.qos.logback.core.OutputStreamAppender` `outputStream.write(byteArray)` as a blocker.

## Expected Behavior
Since `outputStream.write(byteArray)` is blocking I/O operation, so BlockHound should detect this as a blocking call.

## Actual Behavior
Can't detect `ch.qos.logback.core.OutputStreamAppender` `outputStream.write(byteArray)` as a blocker.

## Steps to Reproduce
Any scratch spring boot project with `net.logstash.logback:logstash-logback-encoder:6.4`

## Possible Solution
`reactor.blockhound.integration.LoggingIntegration#applyTo` allowing `ch.qos.logback.classic.Logger#callAppenders` as blocking call. But `callAppenders` eventually call `ch.qos.logback.core.UnsynchronizedAppenderBase#append`.

There are several implementation of `ch.qos.logback.core.UnsynchronizedAppenderBase` abstract class. Some are blocking and some are non-blocking. So, it would be good to remove the following code from `reactor.blockhound.integration.LoggingIntegration#applyTo` method.

https://github.com/reactor/BlockHound/blob/9707f4476c0c05de2ed034d8c57f6fee5769efc3/agent/src/main/java/reactor/blockhound/integration/LoggingIntegration.java#L38-L42

https://github.com/qos-ch/logback/blob/a154cd1b564d436c90a26b8cb1a2e8ffff0a4a47/logback-core/src/main/java/ch/qos/logback/core/OutputStreamAppender.java#L197-L205

## Your Environment

* Reactor version(s) used: 3.3.0.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): logstash-logback-encoder:6.4
* JVM version (`javar -version`): openjdk version "11.0.6"
* OS and version (eg `uname -a`): Ubuntu 18.04 LTS

[I think it's reproducible from any environment]

**Comment by bsideup** [comment]
Hi @rejuan,

It is done for convenience, and you can always tune this behaviour:
https://github.com/reactor/BlockHound/blob/master/docs/customization.md#customization

Also note that BlockHound 1.0.4.RELEASE introduced a new logging integration based on `System.out`/`System.err`:
https://github.com/reactor/BlockHound/blob/master/agent/src/main/java/reactor/blockhound/integration/StandardOutputIntegration.java
