### ISSUE TITLE
Mockito.mock fails with BlockHound

### ISSUE THREAD

**Issue by Mert-Z** [reactor/BlockHound#152]
`Mockito.mock` fails when `blockhound-junit-platform` is added to project dependencies.

## Expected Behavior

Removing `blockhound-junit-platform` from dependencies makes the tests pass. I'd expect tests to pass with BlockHound.

## Actual Behavior

```
[ERROR] testSomeScenario  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
        at SomeServiceUTest.testSomeScenario(SomeServiceUTest.java:32)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@b90c5a5
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 

Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 1.8
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 25.242-b08
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_242-b08
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14.6

Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@30c03473
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/libattach.dylib already loaded in another classloader

```

## Steps to Reproduce

```java
@Test
public void testSomeScenario() {
    mock(Object.class);
}
```

## Possible Solution

Looks like `Byte Buddy` dependency pulled transitively by `mockito-core` doesn't play nicely with the [shaded copy](https://github.com/reactor/BlockHound/blob/9707f4476c0c05de2ed034d8c57f6fee5769efc3/agent/build.gradle#L55) of `Byte Buddy` included in `BlockHound` library.

```
+- org.mockito:mockito-core:jar:3.3.3:test
|  +- net.bytebuddy:byte-buddy:jar:1.10.14:test
|  +- net.bytebuddy:byte-buddy-agent:jar:1.10.14:test
|  \- org.objenesis:objenesis:jar:2.6:test
```

## Your Environment

* `io.projectreactor.tools:blockhound-junit-platform:jar:1.0.4.RELEASE`
* `org.mockito:mockito-core:jar:3.3.3` (via `org.springframework.boot:spring-boot-starter-test:jar:2.3.4.RELEASE`)
* `org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.3.4.RELEASE` (via `org.springframework.boot:spring-boot-starter-webflux:jar:2.3.4.RELEASE`)
* `io.projectreactor:reactor-test:jar:3.3.10.RELEASE`
* 1.8.0_242-b08 OpenJDK 64-Bit Server VM
* Mac OS X 10.14.6

**Comment by bsideup** [comment]
@Mert-Z please report it to Mockito. As to the shaded copy of BB, see #70.

**Comment by Mert-Z** [comment]
@bsideup any chance releasing a `BlockHound` version without shaded `Byte Buddy` included in it?

**Comment by Mert-Z** [comment]
> @bsideup any chance releasing a `BlockHound` version without shaded `Byte Buddy` included in it?

ah sorry ignore me.. just seen this https://github.com/reactor/BlockHound/issues/70#issuecomment-712253375

**Comment by Mert-Z** [comment]
> > @bsideup any chance releasing a `BlockHound` version without shaded `Byte Buddy` included in it?
> 
> ah sorry ignore me.. just seen this [#70 (comment)](https://github.com/reactor/BlockHound/issues/70#issuecomment-712253375)

as a side note, adding JNA to classpath made no difference.

**Comment by bsideup** [comment]
> as a side note, adding JNA to classpath made no difference.

This is weird. Adding JNA makes ByteBuddy prefer the emulated attachment strategy, and it should work fine. Since Mockito is maintained by the same person who created ByteBuddy, I would say reporting the issue to them would be the best play. The reproducer can be simplified to:
1. `BlockHound.install()`
2. `Mockito.mock(Object.class)`

no need to use the junit jupiter integration actually
