### ISSUE TITLE
BlockHound does not detect that any blocking call if i enable spring security @EnableWebFluxSecurity

### ISSUE THREAD

**Issue by rinfimate** [reactor/BlockHound#173]
## Expected Behavior
BlockHound should detect that any blocking call if i enable spring security @EnableWebFluxSecurity

## Actual Behavior
BlockHound does not detect that any blocking call if i enable spring security @EnableWebFluxSecurity

## Steps to Reproduce

```xml
< dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-security</artifactId>
</dependency-->
```

```java
@EnableWebFluxSecurity
public class SecurityConfig {
	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		UserDetails user = User.withUsername("admin").password(passwordEncoder().encode("password")).roles("ADMIN")
				.build();
		return new MapReactiveUserDetailsService(user);
	}

	@Bean
	public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
		http.csrf().disable().authorizeExchange().pathMatchers(HttpMethod.POST, "/mechanics/update").hasRole("ADMIN")
				.pathMatchers("/**").permitAll().and().httpBasic();
		return http.build();
	}

	@Bean
	public PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}
}
```

## Your Environment
* Reactor version(s) used: reactor-core/3.4.3
* Other relevant libraries versions (eg. `netty`, ...): r2dbc-h2/0.8.4, hazelcast, hazelcast-spring, spring-boot/2.4.3
* JVM version (`java -version`): 11.0.10
* OS and version (eg `uname -a`): Windows 10

**Comment by simonbasle** [comment]
What is the "blocking call" that you expect BlockHound should report here? This is not a complete reproducable example without that information.

I'm assuming `BCryptPasswordEncoder.encode(String)` is the one you'd expect to be reported.
But a quick test with a demo boot application shows that the bean-generating method is invoked at application startup on the `main` thread, which doesn't require non-blocking code.

**Comment by rinfimate** [comment]
> What is the "blocking call" that you expect BlockHound should report here? This is not a complete reproducable example without that information.
> 
> I'm assuming `BCryptPasswordEncoder.encode(String)` is the one you'd expect to be reported.
> But a quick test with a demo boot application shows that the bean-generating method is invoked at application startup on the `main` thread, which doesn't require non-blocking code.

Hi Simon,
               It is not the BCryptPasswordEncoder.encode(String) that is the issue. To reproduce this just have any blocking call (E.g Open a file and write to it) in your Reactive controller. Without the above dependencies (spring-boot-starter-security) added to the pom.xml blockhound detects the blocking call. The moment you add (spring-boot-starter-security) dependencies to the pom.xml and the configuration class it does not detect it anymore. If you want I can zip up before and after project zips for you to easily recreate.

**Comment by simonbasle** [comment]
can you verify in which thread the blocking call runs in such a case?

**Comment by simonbasle** [comment]
it seems that introducing spring security causes a switch to `Schedulers.boundedElastic()`. This might be by design, but also might be an overlook because it means that the application is back to creating 1 thread per request... Please discuss with the spring-security team, in any case this is not an issue with BlockHound per se since that particular type of `Scheduler` is explicitly made for blocking calls.

**Comment by rinfimate** [comment]
Sure. Thanks for the quick response. Will raise this with the spring security team

**Comment by simonbasle** [comment]
before you raise an issue with them, have a look at the current guidance (this sounds like a known thing to keep in mind, especially with Basic Authentication):
 - https://docs.spring.io/spring-security/site/docs/current/reference/html5/#authentication-password-storage-history
 - https://github.com/spring-projects/spring-security/issues/7522
