### ISSUE TITLE
`allowBlockingCallsInside` a class

### ISSUE THREAD

**Issue by dkhalanskyjb** [reactor/BlockHound#221]
Allow every method in a class to make blocking calls.

## Motivation

Sometimes we want to claim that a class as a whole is benign, despite it making blocking calls. Example: https://github.com/reactor/BlockHound/blob/master/agent/src/main/java/reactor/blockhound/integration/StandardOutputIntegration.java This particular example is fine, though, as the set of methods is unlikely to change.

In kotlinx.coroutines, we have a set of classes that are safe to use in non-blocking code despite using locks. In order to make BlockHound recognize them as benign, we do the following: https://github.com/Kotlin/kotlinx.coroutines/blob/defd0ec493ebe7b6649892d8f1060fa9e0e602dc/kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt#L101-L140

That's a lot of boilerplate just to say "these three classes are safe"! What led me to file this issue is https://github.com/Kotlin/kotlinx.coroutines/pull/2881, which adds new methods to the list of allowed ones, when in actuality we just mean all of them.

Some of the boilerplate in our integration seems unavoidable to me (though I'm open to a discussion about the other parts of the file as well in case you're interested), but avoiding listing every method of completely benign classes looks like low-hanging fruit for maintainability.

## Desired solution
Some compact API that allows blocking calls inside any (or most?) methods of a class.

**Comment by simonbasle** [comment]
currently 0 resource to work on this, the manual listing is the best approach
