### ISSUE TITLE
Switch testCompile to testImplementation

### ISSUE THREAD

**Issue by fhfelipefh** [reactor/BlockHound#234]
This dependency annotation is not any more compatible with Gradle.

**Comment by simonbasle** [comment]
only actual occurrence I could find was at https://github.com/reactor/BlockHound/blob/e566a5327eb65afcd9a50ba282ee7ef6a678acc7/example/build.gradle#L29

is this what you're talking about?

I'll also change the `testCompile` occurrences in documentation
