### ISSUE TITLE
build a skip or disable feature for individual tests

### ISSUE THREAD

**Issue by loran-steinberger** [reactor/BlockHound#277]
## Motivation
As a user of blockhound, I would like to implement a test which I know will break and commit to my repo.
To prevent this test from breaking my build pipeline, a skip feature would prevent it from being run.

## Desired solution
a utility function or annotation that marks tests as skipped by test runner

**Comment by pderop** [comment]
Hi @loran-steinberger ,

regarding this old issue ...
why not using a BlockHound integration plugin that would allow your test to block without breaking the test ?

Something like this:

```java
package com.example;

public class MyTest {
    static {
        BlockHound.install(b -> {
            b.allowBlockingCallsInside("com.example.MyTest", "block");
        });
    }

    void block() throws InterruptedException {
        Thread.sleep(100);
    }

    @Test
    void testBlockHound2() throws ExecutionException, InterruptedException, TimeoutException {
        Mono.delay(Duration.ofSeconds(1))
                .doOnNext(it -> {
                    try {
                        block(); // this method can block, because we have allowed it to do so
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                })
                .block();
    }
}
```

**Comment by pderop** [comment]
@loran-steinberger ,

I'm closing this one, because as said previously, BlockHound integration plugins can be used in order to avoid a blocking test to fail.
Of course, feel free to reopen if needed !
thanks.
