### ISSUE TITLE
JVM fatal error when in debug mode (jdk1.8.0_60), works with jdk1.8.0_211

### ISSUE THREAD

**Issue by jgrandja** [reactor/BlockHound#37]
When running a simple JUnit test in debug mode with a breakpoint enabled, the following fatal error occurs with JDK 8 (build 1.8.0_60-b27):

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010d046914, pid=33734, tid=16903
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x446914]  Method::checked_resolve_jmethod_id(_jmethodID*)+0xe
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/jgrandja/workspace/issues/oauth2-client-nonblock/ui-app/hs_err_pid33734.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Disconnected from the target VM, address: '127.0.0.1:61502', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

If I disable breakpoints, the test executes without error.

This error only happens in debug mode with at least one breakpoint enabled.

**Comment by bsideup** [comment]
Hi @jgrandja,

Thanks for reporting!
Is it always reproducible? Do you think you can share the project?

I just tried debugging the tests with JDK 1.8 (Although mine is much newer, `1.8.0_212-b03`) and it works fine

**Comment by jgrandja** [comment]
Hi @bsideup 

Yes, I'm able to reproduce each time.

Here is the [repo](https://github.com/jgrandja/oauth2-client-nonblock).

Run this [test](https://github.com/jgrandja/oauth2-client-nonblock/blob/master/ui-app/src/test/java/sample/Tests.java) in debug mode and put a break point [here](https://github.com/jgrandja/oauth2-client-nonblock/blob/master/ui-app/src/test/java/sample/Tests.java#L144).

This will reproduce - at least with the JVM version I have.

**Comment by bsideup** [comment]
@jgrandja thanks a lot for providing the reproducer! It does not fail on AdoptOpenJDK 1.8.0_212-b03, I will try others.
Do you think you can update your JDK meanwhile? Maybe there is a bug in the build you're using that was fixed in newer versions?

**Comment by jgrandja** [comment]
Yeah, I haven't updated my JDK in a while. I'll update and try again and let you know.

**Comment by bsideup** [comment]
@jgrandja any updates? :)

**Comment by jgrandja** [comment]
@bsideup I just tested with `jdk1.8.0_211` and it works fine. Looks like a bug in older jdk version I had. Feel free to close this.

**Comment by bsideup** [comment]
Ok, thanks! 👍
