### ISSUE TITLE
[Question] Is this the right way to customize blockhound-junit-platform?

### ISSUE THREAD

**Issue by dsibilio** [reactor/BlockHound#50]
*Not really an issue, but I couldn't find a gitter channel for BlockHound where I would've asked this question otherwise :)*

I'm playing around with **BlockHound JUnit Platform** for a little demo based on Project Reactor (https://github.com/dsibilio/blockhound-demo).

While fiddling with it, I noticed that the `ch.qos.logback.classic.Logger#buildLoggingEventAndAppend` got flagged downstack due to some blocking IO.

Of course I wanted to allow this method but I couldn't find a way to customize BlockHound before initialization since it gets done for me by the [BlockHoundTestExecutionListener.java](https://github.com/reactor/BlockHound/blob/master/junit-platform/src/main/java/reactor/blockhound/junit/platform/BlockHoundTestExecutionListener.java), so I had to:

- replace blockhound-junit-platform with blockhound dependency;
- write my own [TestExecutionListener](https://github.com/dsibilio/blockhound-demo/blob/master/src/test/java/it/dsibilio/blockhounddemo/config/CustomBlockHoundTestListener.java) with the forementioned method set as allowed;
- add the [META-INF/services/[...]TestExecutionListener](https://github.com/dsibilio/blockhound-demo/blob/master/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener) file that lists my implementation for SPI dependency injection.

So, as per title, **is this the right way to allow/disallow custom methods when wanting to use blockhound-junit-platform?** Or is there something obvious that I might've missed?

Thanks in advance :)

**Comment by bsideup** [comment]
Hi! There is much easier way: SPI! :)

https://github.com/reactor/BlockHound/blob/master/docs/custom_integrations.md

You just need to create an integration and META-INF/services/... file

Example:
https://github.com/reactor/reactor-netty/blob/enable_blockhound/src/test/java/reactor/netty/NettyTestBlockHoundIntegration.java

**Comment by dsibilio** [comment]
Thanks, didn't notice the empty varargs install method loaded all the integrations.
Integrated the change in my demo and everything still works, much better.

Thank you! :)

**Comment by bsideup** [comment]
Good! 

I'm going to close the issue (the SPI mechanism is mentioned [in the docs](https://github.com/reactor/BlockHound/blob/master/docs/customization.md#customization) too)

**Comment by bsideup** [comment]
FYI I created a Gitter room :) https://gitter.im/reactor/BlockHound
