### ISSUE TITLE
Getting Exceptions when stop application

### ISSUE THREAD

**Issue by StVl** [reactor/BlockHound#74]
Hello, i try to use BlockHound, what i do:
1) add line BlockHound.install () to my SpringBootApplication class
2) start application
3) stop application

what i get:
![image](https://user-images.githubusercontent.com/17905670/71176265-8753ec00-227a-11ea-9dd6-a88202f4e0e4.png)
which is remarkable, I don't see a line of code with a lock on it.

can you help me with that?

**Comment by bsideup** [comment]
Hi.

Netty, on shutdown, will use `Thread.sleep` to await the shutdown. The latest version of Netty (also reactor-netty) have it whitelisted.

You you can't update, you can whitelist it yourself, see https://github.com/netty/netty/pull/9687/files#r337891977 for more context.

Also, not sure why on the screenshot the exception stacktrace is truncated, I guess your logger is configured this way.

**Comment by StVl** [comment]
Спасибо, Егор!

**Comment by bsideup** [comment]
I am Sergei ;)
