### ISSUE TITLE
Not getting exception in blocking call

### ISSUE THREAD

**Issue by Poorva17** [reactor/BlockHound#83]
Hello, 

I want to use blockhound for my scala application. To try out capabilities I have written following sample,

```scala
import reactor.blockhound.BlockHound

object Main extends App {
  val builder = BlockHound.builder()
  builder.install()
  builder.disallowBlockingCallsInside(
    "scala.Console$",
    "println"
  )
  builder.blockingMethodCallback(m => {
    new Exception(m.toString).printStackTrace()
  })
  builder.blockingMethodCallback(println)
  println("************************")
}
```

## Expected Behaviour
I am dis allowing blocking call in println So I am expecting blockhound to throw exception. 

## Actual Behaviour
No exception is thrown. Program runs and prints ********

## Environment

* Reactor version(s) used: 1.0.2.RELEASE
* JVM version (`javar -version`): openjdk version "11.0.2"
* OS and version (eg `uname -a`): Darwin Kernel Version 19.2.0

Is there any sample scala project where I can look for usage of blockhound.

Note - Application runs from sbt console. But I am not getting intelliJ support while writing and running code. Might be my machine issue. 
I have added Dependency in build.sbt ```"io.projectreactor.tools" % "blockhound"            % "1.0.2.RELEASE"```

**Comment by bsideup** [comment]
Hello @Poorva17,

BlockHound only reports blocking calls when they are performed from non-blocking threads. You're running everything on the main thread, which is not marked as non-blocking.

Also, calling builder's methods after you perform `install()` is a no-op.

The correct pattern for customization is:
```java
BlockHound.install(builder -> {
    builder.blockingMethodCallback(m -> {
        new Exception(m.toString()).printStackTrace();
    });
});
```

**Comment by Poorva17** [comment]
Thank you @bsideup for reply. 

I have corrected my code based on your response. It looks like following:

```scala
import java.util.concurrent.Executors
import java.util.function.Predicate

import reactor.blockhound.BlockHound

import scala.concurrent.ExecutionContext

object Main extends App {

  private val ec: ExecutionContext = ExecutionContext.fromExecutorService(Executors.newSingleThreadScheduledExecutor)

  BlockHound.install(builder => {
    builder.nonBlockingThreadPredicate(p => {
      p.or(Predicate.isEqual(classOf[ExecutionContext].isInstanceOf))
    })
    builder.blockingMethodCallback(m => {
      new Exception(m.toString).printStackTrace()
    })
    builder.disallowBlockingCallsInside(
      "scala.concurrent.ExecutionContext",
      "execute"
    )
  })

  private val runnable: Runnable = new Runnable {
    override def run(): Unit = {
      println(s"hello ${Thread.currentThread.getName()}");
      Thread.sleep(2000)
    }
  }
  ec.execute(runnable)
}

```
## Expected Behaviour - 
As I am printing hello and thread name it shows me right thread name which is `hello pool-1-thread-1` NOT main thread. I am expecting that blockhound will print exception stack trace as I am doing blocking operation (Thread.sleep(2000)). 

## Actual Behaviour - 
Program is running without any exception.  

Am I missing something?

**Comment by bsideup** [comment]
I don't think `ExecutionContext` is the correct type of the threads.

Consider putting a breakpoint in your `run()` and checking the current thread.


FYI `disallowBlockingCallsInside` in your example is not needed.

**Comment by Poorva17** [comment]
Thanks a lot @bsideup. 😄  I got expected behaviour. I will explore blockhound further. 👍

**Comment by bsideup** [comment]
Yay! Happy to hear that, and don't hesitate to report and ask questions! 👍 

FYI you may also find this article helpful:
https://bsideup.github.io/posts/blockhound_with_akka/

**Comment by Poorva17** [comment]
Hi @bsideup ,
I am referring to your blog and exploring blockhound for akka actor. 

I have configured blockhound to monitor my akka actor using predicate
```scala
class AkkaIntegration() extends BlockHoundIntegration {

  override def applyTo(builder: Builder): Unit = {
    builder
      .nonBlockingThreadPredicate(p => { p.or(thread => {
        thread.getName.contains("myactorsystem-akka.actor.default-dispatcher")})
      })
      .disallowBlockingCallsInside(
        "akka.dispatch.forkjoin.ForkJoinTask",
        "doExec"
      )
      .allowBlockingCallsInside("jdk.internal.misc.Unsafe", "park")
      .allowBlockingCallsInside("java.util.concurrent.ForkJoinWorkerThread", "run")
      .allowBlockingCallsInside("scala.Console$", "println")
      .blockingMethodCallback(method => new Exception(method.toString).printStackTrace())
  }
}
```

When I run my application with actor integration blockhound report blocking call for following multiple times,

```
java.lang.Exception: jdk.internal.misc.Unsafe#park
	at esw.ocs.impl.blockhound.EswBlockHoundIntegration.$anonfun$eswBlockHoundBuilder$2(EswBlockHoundIntegration.scala:17)
	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:382)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89)
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
  | => eat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
I have added  jdk.internal.misc.Unsafe.park in allow blocking call but still my app console is shows lot of stack trace for same exception.  I am not able to understand what's wrong in my implementation.
